name: 'walmart_bi'
version: '1.0.0'
config-version: 2

profile: 'walmart_bi'  # must match a profile in ~/.dbt/profiles.yml (dbt Core)
                        # — not needed if you're using dbt Cloud, which
                        # manages the connection in its UI instead.

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  walmart_bi:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

snapshots:
  walmart_bi:
    +target_schema: staging  # dbt snapshots require a fixed target schema